image: Visual Studio 2017

version: 0.0.0-{build}
build_script:  
  - ps: .\build.ps1 -Target "Default"

artifacts:
  - path: artifacts\*.nupkg
    name: Packages

skip_tags: false
skip_branch_with_pr: true
